#!/bin/bash

# The cmslpc condor schedulers are now lpcschedd3, lpcschedd4, and lpcschedd5.
echo Condor Jobs status for $USER:
echo "-------------------------------"
condor_q | grep "Total for $(whoami)" | awk '{j+=$4;c+=$6;re+=$8;i+=$10;ru+=$12;h+=$14;s+=$16;k++}{print "lpcschedd " k+2 ":", substr($0, index($0,$4))}END{print "-------------------------------"}END{print $1 ":", j, $5, c, $7, re, $9, i, $11, ru, $13, h, $15, s, $17 }'
echo "-------------------------------"
condor_userprio | awk "/gov/{n+=1}/$USER/{p=n}END{print \"Your position:\", p \"   Total users:\", n}"
