#!/bin/bash
condor_q | grep "Total for $USER" | awk '{j+=$4;c+=$6;re+=$8;i+=$10;ru+=$12;h+=$14;s+=$16}{print $0}END{print "---------------"}END{print $1, $2, $3, j, $5, c, $7, re, $9, i, $11, ru, $13, h, $15, s, $17 }'

